service: chatbot-api

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    GROQ_API_KEY: ${env:GROQ_API_KEY}

functions:
  api:
    handler: lambda_handler.handler
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

plugins:
  - serverless-python-requirements